

export type Genre =
  | 'mixed'
  | 'nature'
  | 'kitchen'
  | 'home'
  | 'tech'
  | 'travel'
  | 'sports'
  | 'emotions'
  | 'verbs'
  | 'science'
  | 'music'
  | 'fashion'
  | 'school';

export const GENRE_LABELS: Record<Genre, { emoji: string; label: string }> = {
  mixed: { emoji: '🎲', label: 'Mixed' },
  nature: { emoji: '🌿', label: 'Nature & Wildlife' },
  kitchen: { emoji: '🍕', label: 'The Kitchen' },
  home: { emoji: '🏠', label: 'The Modern Home' },
  tech: { emoji: '💻', label: 'Tech & Coding' },
  travel: { emoji: '✈️', label: 'Travel & Geography' },
  sports: { emoji: '⚽', label: 'Sports & Fitness' },
  emotions: { emoji: '💭', label: 'Emotions & Feelings' },
  verbs: { emoji: '⚡', label: 'Action Verbs' },
  science: { emoji: '🔬', label: 'Science & Space' },
  music: { emoji: '🎵', label: 'Music & Sound' },
  fashion: { emoji: '👗', label: 'Fashion & Style' },
  school: { emoji: '📚', label: 'School & Learning' },
};

export const GENRE_WORDS: Record<Genre, string[]> = {

  mixed: [],

  nature: [
    'trees', 'birds', 'tiger', 'flora', 'storm', 'cliff', 'coral', 'eagle',
    'whale', 'crane', 'goose', 'snake', 'stork', 'bison', 'moose', 'llama',
    'otter', 'raven', 'swift', 'trout', 'shark', 'heron', 'viper', 'panda',
    'zebra', 'koala', 'camel', 'hyena', 'sloth', 'gecko', 'robin', 'moths',
    'squid', 'finch', 'perch', 'quail', 'dingo', 'hippo', 'fungi', 'frost',
    'grove', 'peaks', 'reeds', 'thorn', 'bloom', 'creek', 'marsh', 'woods',
    'field', 'ferns', 'grass', 'ocean', 'beach', 'river', 'stone', 'cloud',
    'winds', 'waves', 'earth', 'seeds', 'roots', 'vines', 'shore', 'caves',
    'hills', 'lakes', 'briar', 'berry', 'tulip', 'shrub', 'cedar', 'birch',
    'aspen', 'maple', 'olive', 'palms', 'dunes', 'delta', 'swamp', 'lions',
    'bears', 'ducks', 'frogs', 'sheep', 'horse', 'mouse', 'hawks', 'geese',
    'clams', 'crabs', 'snail', 'moles', 'ivory', 'polar', 'night', 'stars',
    'sunny', 'foggy', 'misty', 'rainy', 'humid', 'snowy', 'windy', 'flood',
    'tides', 'plant', 'leafy', 'rocky', 'sandy', 'muddy', 'mossy', 'steep',
    'creek', 'brook', 'ledge', 'bluff', 'ridge', 'knoll', 'gulch', 'glade',
    'trail', 'range', 'basin', 'inlet', 'fjord', 'atoll', 'islet', 'coast',
  ],

  kitchen: [
    'bread', 'spice', 'pasta', 'steak', 'knife', 'plums', 'lemon', 'cream',
    'sugar', 'melon', 'sauce', 'olive', 'grape', 'flour', 'honey', 'candy',
    'toast', 'salad', 'curry', 'fruit', 'juice', 'wheat', 'crust', 'broth',
    'roast', 'dough', 'beans', 'peach', 'bacon', 'cocoa', 'basil', 'mango',
    'mocha', 'kebab', 'gravy', 'clove', 'guava', 'crepe', 'bagel', 'pizza',
    'maple', 'berry', 'nacho', 'chili', 'grain', 'seeds', 'sweet', 'stews',
    'meals', 'snack', 'taste', 'plate', 'forks', 'spoon', 'bowls', 'mixer',
    'grind', 'blend', 'saute', 'steam', 'brine', 'filet', 'pecan', 'thyme',
    'diner', 'feast', 'rolls', 'yeast', 'cider', 'syrup', 'salsa', 'onion',
    'prune', 'dates', 'flask', 'ladle', 'whisk', 'scone', 'torte', 'glaze',
    'stock', 'minty', 'tangy', 'zesty', 'smoky', 'fried', 'dried', 'baked',
    'press', 'grill', 'poach', 'chunk', 'churn', 'nutty', 'crisp', 'flaky',
    'chewy', 'puree', 'brisk', 'herbs', 'cumin', 'anise', 'carom', 'poppy',
    'aroma', 'drink', 'water', 'salty', 'sushi', 'ramen', 'naans', 'wraps',
    'tacos', 'pitas', 'mochi', 'jelly', 'fudge', 'tarts', 'pears', 'apple',
    'panko', 'crumb', 'diced', 'soups', 'chops', 'ribs', 'wings', 'patty',
  ],

  home: [
    'chair', 'table', 'shelf', 'couch', 'light', 'phone', 'radio', 'clock',
    'doors', 'floor', 'walls', 'lamps', 'frame', 'glass', 'tiles', 'paint',
    'brush', 'towel', 'sofas', 'desks', 'piano', 'drape', 'blind', 'vases',
    'rooms', 'roofs', 'porch', 'halls', 'attic', 'decor', 'alarm', 'cable',
    'panel', 'meter', 'pipes', 'plugs', 'wires', 'drain', 'stove', 'sweep',
    'mower', 'books', 'paper', 'boxes', 'coats', 'hooks', 'stair', 'fence',
    'gates', 'brick', 'steel', 'stone', 'plant', 'herbs', 'patio', 'decks',
    'bench', 'dusty', 'clean', 'shiny', 'fresh', 'power', 'solar', 'heats',
    'cools', 'humid', 'aired', 'bolts', 'nails', 'screw', 'glued', 'knobs',
    'leaky', 'fixed', 'cedar', 'maple', 'brass', 'ivory', 'cream', 'beige',
    'white', 'black', 'amber', 'matte', 'sleek', 'thick', 'spare', 'tiled',
    'store', 'stack', 'trunk', 'chest', 'stand', 'mount', 'latch', 'hinge',
    'ledge', 'foyer', 'nooks', 'duvet', 'quilt', 'sheet', 'shade', 'strap',
    'basin', 'valve', 'grout', 'morta', 'plank', 'beams', 'gable', 'eaves',
    'draft', 'broom', 'cloth', 'satin', 'linen', 'suede', 'wheel', 'lever',
    'timer', 'gauge', 'motor', 'relay', 'fuses', 'watts', 'rated', 'smart',
  ],

  tech: [
    'array', 'logic', 'proxy', 'stack', 'cache', 'input', 'build', 'debug',
    'class', 'nodes', 'query', 'fetch', 'parse', 'async', 'await', 'yield',
    'scope', 'const', 'loops', 'index', 'shift', 'merge', 'clone', 'token',
    'bytes', 'ascii', 'print', 'shell', 'linux', 'ports', 'cloud', 'patch',
    'trunk', 'repos', 'regex', 'state', 'event', 'model', 'route', 'hooks',
    'props', 'types', 'error', 'tests', 'mocks', 'setup', 'pixel', 'fonts',
    'theme', 'style', 'grids', 'cards', 'modal', 'toast', 'hover', 'click',
    'forms', 'links', 'menus', 'icons', 'badge', 'chart', 'draft', 'admin',
    'roles', 'users', 'login', 'crypt', 'block', 'chain', 'smart', 'swift',
    'react', 'redis', 'mongo', 'flask', 'keras', 'numpy', 'depth', 'width',
    'batch', 'epoch', 'layer', 'dense', 'train', 'label', 'graph', 'heaps',
    'queue', 'deque', 'pivot', 'sorts', 'codec', 'codec', 'float', 'round',
    'split', 'strip', 'raise', 'break', 'while', 'super', 'param', 'value',
    'field', 'table', 'views', 'inner', 'outer', 'count', 'group', 'apply',
    'sleep', 'spawn', 'forks', 'pipes', 'mutex', 'locks', 'procs', 'flags',
    'mount', 'chmod', 'stdin', 'write', 'reads', 'flush', 'close', 'bind',
  ],

  travel: [
    'plane', 'coast', 'roads', 'train', 'hotel', 'india', 'paris', 'tokyo',
    'cairo', 'delhi', 'dubai', 'nauru', 'spain', 'italy', 'egypt', 'chile',
    'nepal', 'kenya', 'ghana', 'japan', 'china', 'qatar', 'tonga', 'gabon',
    'benin', 'haiti', 'samoa', 'palau', 'libya', 'congo', 'malta', 'wales',
    'berne', 'hanoi', 'abuja', 'dakar', 'quito', 'sucre', 'rabat', 'minsk',
    'docks', 'ferry', 'ships', 'ports', 'wharf', 'taxis', 'buses', 'rails',
    'route', 'metro', 'depot', 'tower', 'plaza', 'ruins', 'tombs', 'forts',
    'arena', 'domes', 'canal', 'beach', 'isles', 'ridge', 'basin', 'delta',
    'fjord', 'atlas', 'globe', 'north', 'south', 'guide', 'stamp', 'lodge',
    'cabin', 'suite', 'trail', 'camps', 'hikes', 'tours', 'boats', 'yacht',
    'kayak', 'cross', 'drift', 'roams', 'treks', 'climb', 'miles', 'bound',
    'chart', 'lanes', 'paths', 'walks', 'lands', 'realm', 'quest', 'visit',
    'nomad', 'rover', 'maps', 'oasis', 'gorge', 'bluff', 'cliff', 'creek',
    'grove', 'shore', 'scene', 'views', 'stays', 'local', 'feast', 'spice',
    'music', 'dance', 'crowd', 'night', 'dawn', 'dusk', 'peaks', 'lakes',
    'river', 'ocean', 'woods', 'urban', 'rural', 'trade', 'world', 'photo',
  ],

  sports: [
    'coach', 'match', 'field', 'track', 'score', 'rugby', 'sweat', 'medal',
    'relay', 'skate', 'vault', 'goals', 'arena', 'court', 'serve', 'rally',
    'clubs', 'kayak', 'teams', 'races', 'shots', 'speed', 'throw', 'block',
    'punch', 'rider', 'swing', 'slide', 'trail', 'climb', 'surfs', 'darts',
    'pools', 'cycle', 'squad', 'grips', 'guard', 'motor', 'jumps', 'lifts',
    'moves', 'round', 'saves', 'games', 'balls', 'plays', 'pitch', 'catch',
    'bouts', 'heats', 'dives', 'kicks', 'fouls', 'draws', 'bench', 'drill',
    'rinks', 'champ', 'title', 'belts', 'rings', 'preps', 'train', 'power',
    'agile', 'quick', 'swift', 'tough', 'feint', 'lunge', 'press', 'squat',
    'plank', 'crush', 'racer', 'boxer', 'diver', 'rowed', 'sails', 'draft',
    'timer', 'clock', 'start', 'final', 'reign', 'chase', 'prize', 'glory',
    'honor', 'crowd', 'cheer', 'stand', 'boots', 'glove', 'stick', 'blade',
    'pucks', 'lanes', 'steer', 'reins', 'whips', 'hurls', 'volts', 'fleet',
    'stamp', 'level', 'strap', 'bands', 'grips', 'chalk', 'mound', 'bases',
    'homer', 'bunts', 'steal', 'slide', 'brawl', 'score', 'goals', 'duels',
    'table', 'paddy', 'ovals', 'sport', 'ranks', 'seeds', 'heady', 'fired',
  ],

  emotions: [
    'happy', 'angry', 'proud', 'upset', 'fears', 'bliss', 'grief', 'shame',
    'brave', 'nervy', 'moody', 'jolly', 'gloom', 'dread', 'eager', 'bored',
    'trust', 'doubt', 'guilt', 'sorry', 'peace', 'calms', 'tense', 'alarm',
    'shock', 'yearn', 'crave', 'loath', 'scorn', 'spite', 'pains', 'aches',
    'weary', 'tired', 'irate', 'livid', 'cross', 'manic', 'giddy', 'dizzy',
    'bland', 'stale', 'heavy', 'empty', 'blunt', 'harsh', 'cruel', 'sweet',
    'loved', 'cared', 'honor', 'valor', 'faith', 'grace', 'mercy', 'whole',
    'aloof', 'alone', 'quiet', 'still', 'fiery', 'fired', 'moved', 'wound',
    'heals', 'mends', 'bonds', 'unity', 'moral', 'noble', 'royal', 'pride',
    'vexed', 'flaws', 'inner', 'depth', 'sense', 'force', 'vigor', 'might',
    'gloat', 'snide', 'blues', 'tears', 'smile', 'smirk', 'frown', 'sighs',
    'elate', 'pangs', 'cheer', 'mirth', 'angst', 'agony', 'wrath', 'scowl',
    'shock', 'aghast', 'qualm', 'pique', 'brood', 'sulks', 'mourn', 'grins',
    'gleam', 'gushy', 'lusty', 'testy', 'edgy', 'jumpy', 'antsy', 'frank',
    'stern', 'rigid', 'stoic', 'meek', 'timid', 'coyly', 'wryly', 'keenly',
    'truly', 'madly', 'sadly', 'oddly', 'newly', 'fully', 'badly', 'dimly',
  ],

  verbs: [
    'drive', 'write', 'think', 'climb', 'break', 'start', 'build', 'carry',
    'catch', 'chase', 'cheer', 'claim', 'clean', 'close', 'count', 'cover',
    'crash', 'dance', 'dream', 'drink', 'erase', 'feast', 'fight', 'float',
    'focus', 'force', 'forge', 'grasp', 'grind', 'guard', 'guide', 'hurry',
    'judge', 'knock', 'laugh', 'learn', 'leave', 'march', 'match', 'paint',
    'plant', 'press', 'prove', 'raise', 'reach', 'reign', 'roast', 'score',
    'serve', 'shake', 'share', 'shine', 'shoot', 'shout', 'sleep', 'slide',
    'solve', 'spark', 'speak', 'spend', 'split', 'spray', 'stand', 'steal',
    'steer', 'stick', 'sting', 'storm', 'study', 'sweep', 'swing', 'teach',
    'thank', 'throw', 'touch', 'trade', 'train', 'treat', 'trust', 'twist',
    'unite', 'voice', 'wager', 'waste', 'watch', 'weave', 'yield', 'blend',
    'boost', 'bound', 'brace', 'carve', 'craft', 'crush', 'dodge', 'drain',
    'dwell', 'fling', 'flush', 'glide', 'greet', 'hover', 'kneel', 'latch',
    'mount', 'nudge', 'plead', 'pluck', 'point', 'posed', 'rinse', 'scrub',
    'seize', 'shrug', 'skim', 'slash', 'smash', 'sneak', 'soar', 'stall',
    'stoop', 'surge', 'swore', 'trace', 'wield', 'wound', 'wrote', 'cling',
  ],

  science: [
    'atoms', 'cells', 'genes', 'orbit', 'lunar', 'solar', 'stars', 'space',
    'force', 'mass', 'watts', 'volts', 'ohms', 'quark', 'prism', 'laser',
    'acids', 'bases', 'bonds', 'ionic', 'moles', 'salts', 'steam', 'vapor',
    'dense', 'solid', 'fluid', 'gases', 'waves', 'light', 'sound', 'field',
    'depth', 'speed', 'pulse', 'forms', 'phase', 'decay', 'gamma', 'alpha',
    'sigma', 'theta', 'delta', 'omega', 'probe', 'rover', 'comet', 'pluto',
    'venus', 'earth', 'rings', 'moons', 'dwarf', 'giant', 'white', 'radio',
    'radar', 'sonar', 'scans', 'beams', 'focus', 'optic', 'fiber', 'diode',
    'anode', 'watts', 'hertz', 'joule', 'tesla', 'micro', 'macro', 'hyper',
    'ultra', 'infra', 'inter', 'outer', 'inner', 'cross', 'chain', 'helix',
    'clone', 'virus', 'fungi', 'brain', 'nerve', 'spine', 'organ', 'liver',
    'renal', 'flora', 'fauna', 'genus', 'phyla', 'class', 'order', 'toxic',
    'tests', 'trial', 'proof', 'study', 'model', 'scale', 'graph', 'chart',
    'value', 'ratio', 'units', 'basic', 'total', 'level', 'range', 'error',
    'yield', 'input', 'cycle', 'react', 'noise', 'shift', 'drift', 'trace',
    'blend', 'alloy', 'steel', 'oxide', 'silky', 'glass', 'cubic', 'polar',
  ],

  music: [
    'beats', 'drums', 'piano', 'viola', 'flute', 'banjo', 'sitar', 'chime',
    'bells', 'songs', 'notes', 'chord', 'tempo', 'pitch', 'tunes', 'lyric',
    'music', 'vocal', 'voice', 'sound', 'audio', 'album', 'track', 'bands',
    'stage', 'shows', 'dance', 'rhyme', 'verse', 'meter', 'minor', 'major',
    'sharp', 'flats', 'scale', 'modal', 'tones', 'bass', 'treble', 'range',
    'swing', 'solos', 'duets', 'choir', 'opera', 'genre', 'blues', 'metal',
    'jazzy', 'punks', 'indie', 'disco', 'house', 'tango', 'salsa', 'waltz',
    'polka', 'riffs', 'licks', 'strum', 'pluck', 'bowed', 'blown', 'shaky',
    'crowd', 'arena', 'tours', 'gig', 'vibes', 'break', 'drops', 'fades',
    'mixes', 'loops', 'synth', 'organ', 'cello', 'horns', 'brass', 'reeds',
    'snare', 'cybal', 'pedal', 'amps', 'cable', 'muted', 'forte', 'largo',
    'presto', 'vivid', 'trill', 'slide', 'grace', 'holds', 'rests', 'staff',
    'clefs', 'signs', 'score', 'sheet', 'ledge', 'parts', 'hymns', 'psalm',
    'harp', 'oboes', 'tabla', 'gongs', 'pipes', 'kazoo', 'harps', 'tuned',
    'muted', 'crisp', 'warm', 'thick', 'dense', 'clear', 'sharp', 'sweet',
    'noise', 'echo', 'layer', 'depth', 'remix', 'vinyl', 'radio', 'aired',
  ],

  fashion: [
    'dress', 'shirt', 'jeans', 'skirt', 'shoes', 'boots', 'heels', 'flats',
    'coats', 'scarf', 'belts', 'style', 'trend', 'vogue', 'chic', 'sleek',
    'plaid', 'denim', 'linen', 'satin', 'suede', 'tweed', 'laced', 'knits',
    'cloth', 'fiber', 'weave', 'drape', 'pleat', 'frays', 'seams', 'hems',
    'cuffs', 'lapel', 'patch', 'print', 'polka', 'flora', 'color', 'black',
    'white', 'ivory', 'beige', 'coral', 'mauve', 'rouge', 'blush', 'olive',
    'khaki', 'amber', 'cream', 'pearl', 'model', 'poses', 'crowd', 'shows',
    'brand', 'label', 'sizes', 'silks', 'sheer', 'matte', 'gloss', 'toned',
    'smart', 'sharp', 'fancy', 'plain', 'rusty', 'faded', 'retro', 'fresh',
    'urban', 'boho', 'glam', 'edgy', 'posh', 'regal', 'royal', 'noble',
    'loops', 'studs', 'rings', 'chain', 'clasp', 'beads', 'charm', 'gems',
    'jewel', 'tiara', 'crown', 'brodn', 'badge', 'crest', 'motif', 'lines',
    'totes', 'pouch', 'purse', 'bags', 'cases', 'wraps', 'shawl', 'hoods',
    'beret', 'visor', 'derby', 'crown', 'bands', 'knots', 'braid', 'curls',
    'swept', 'sleek', 'frame', 'shape', 'forms', 'panel', 'yokes', 'gores',
    'lined', 'trim', 'bound', 'piped', 'darts', 'tucks', 'flare', 'flowy',
  ],

  school: [
    'books', 'class', 'study', 'learn', 'teach', 'notes', 'essay', 'exams',
    'marks', 'grade', 'tests', 'chalk', 'board', 'desks', 'ruler', 'pens',
    'paper', 'print', 'reads', 'write', 'spell', 'count', 'think', 'solve',
    'proof', 'graph', 'chart', 'ratio', 'angle', 'curve', 'maths', 'lines',
    'words', 'nouns', 'verbs', 'preps', 'tense', 'voice', 'prose', 'verse',
    'rhyme', 'story', 'novel', 'tales', 'fable', 'drama', 'stage', 'scene',
    'paint', 'brush', 'color', 'music', 'songs', 'dance', 'parts', 'roles',
    'teams', 'clubs', 'group', 'pairs', 'seats', 'rows', 'halls', 'rooms',
    'bench', 'shelf', 'stack', 'files', 'forms', 'rules', 'codes', 'plans',
    'goals', 'focus', 'tasks', 'quest', 'trial', 'prize', 'award', 'honor',
    'badge', 'level', 'track', 'field', 'court', 'pools', 'games', 'match',
    'score', 'point', 'guide', 'coach', 'staff', 'heads', 'chief', 'clerk',
    'terms', 'dates', 'times', 'hours', 'weeks', 'month', 'daily', 'early',
    'first', 'final', 'basic', 'total', 'extra', 'major', 'minor', 'model',
    'value', 'ideas', 'basis', 'topic', 'theme', 'scope', 'depth', 'range',
    'sense', 'skill', 'craft', 'known', 'given', 'shown', 'found', 'built',
  ],
};
